theme: jekyll-theme-midnight
title: [Ouankou's LeetCode Solutions]
description: [This blog includes my solutions to LeetCode questions and some explanations.]
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
